Description: ACC EC2 Instance Role 
Resources:
    EC2InstanceRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    EC2InstanceProfile:
      Type: 'AWS::IAM::InstanceProfile'
      Properties:
        Path: /
        Roles:
          - !Ref EC2InstanceRole
Outputs:
    EC2InstanceProfile: 
        Description: EC2 Instance Profile
        Value: !Ref EC2InstanceProfile
        Export:
            Name: acc-vpc1-EC2-instanceprofile
    EC2InstanceRole: 
        Description: EC2 Instance Role
        Value: !Ref EC2InstanceRole
        Export:
            Name: acc-vpc1-EC2-instancerole